IshentRas/cookbook-openshift3

attributes/default.rb, recipes/master.rb, recipes/master_cluster.rb, recipes/master_standalone.rb, recipes/node.rb
We would like an option to hold the version of the atomic host RPM.  This would ensure stability while building out nodes within a cluster.
=> Pin the OSEv3 RPM version

attributes/default.rb
Default behaviour was:
major version: 1.3
deployment type: enterprise
because at the time of setting the major version deployment type was unset. I assume this wasn't the intended default.
=> Bugfix: default to enterprise before ternary operator

recipes/master_config_post.rb
Hi @IshentRas ,
This PR fixes the guards that were recently added in recipe[master_config_post] to prevent setting node schedulability or labels when the node is declared in node_servers but is not online yet.
The syntax:
```ruby
not_if do
condition1
condition2
end
```
Should not be valid in Ruby (because the block will evaluate condition1 but ignore its return value).
I have fixed it to the following syntax:
```ruby
not_if do
condition1 &&
condition2
end
```
=> Fix schedulability and node-labelling guards

attributes/default.rb
This PR removes a duplicate attribute found while trying the openshift_HA mode.
=> Remove duplicate 'etcd_listen_client_urls' attribute.

templates/default/master.yaml.erb
This PR comes as follow up to this comment https://github.com/IshentRas/cookbook-openshift3/pull/38#issuecomment-270134239 in #38 .
It ensures consistency between your last commit which made etcd listen to `etcd_server['ipaddress']` and the current openshift3 master configuration which reaches the etcd server by fqdn in the current code.
On a blank Vagrant VM, the fqdn gets a "free" /etc/hosts entry pointing to 127.0.0.1, so if I configure:
```ruby
ETCD_NODES = [
{ 'ipaddress' => '192.168.33.220', 'fqdn' => 'master' }
]
```
in my Vagrantfile then etcd will listen on '192.168.33.220' while the openshift master will look for etcd at fqdn 'master' which resolves to 127.0.0.1 in /etc/hosts.
I have checked that reaching the etcd by ipaddress does not break certificate verification.
=> Fix etcd URLs in master.yaml when openshift_HA

attributes/default.rb, templates/default/master.yaml.erb
Please review my PR for the possibility to have additional managedNames in the master config yaml.  It is our plan to have a cicd service account auto-created for each new project.  We will bind policy to that account in our admin api service.   
Keith
=> More managed names

.gitignore, .kitchen.yml, README.md, test/inspec/cluster-native/services_test.rb, test/inspec/shared/00_docker_test.rb, test/inspec/shared/10_installation_test.rb, test/inspec/shared/11_functioning_openshift_test.rb, test/inspec/shared/20_feature_attribute_labels_test.rb, test/inspec/standalone/services_test.rb, test/integration/default/serverspec/default_spec.rb, test/integration/helpers/serverspec/spec_helper.rb, test/roles/openshift3-base.json
As promised in https://github.com/IshentRas/cookbook-openshift3/issues/41#issuecomment-270339997, I have cleaned up and ported my own integration tests for this cookbook.
What is tested:
- the basic openshift master/node deployment, in both standalone and cluster-native modes
- the handling of the `labels` and `schedulable` node attributes.
- docker logging configuration via `node['cookbook-openshift3']['docker_log_driver']`
What is not tested (yet):
- hosted registry and router deployment (I don't use the feature yet)
- example deployment (it would be trivial to add though)
- storage provisioning feature
- configuring htpasswd users (I will add the test when I port my wrapper cookbook to use the feature)
Feel free to play with the PR and leave your comments here.
=> Added kitchen inspec integration tests

providers/openshift_deploy_registry.rb
This PR fixes a typo which results in the docker registry not being created with the expected node-selector parameter.
I spotted this one while porting to this cookbook my integration tests for hosted router and registry (coming soon in separate PR).
=> Typo fix in openshift_deploy_registry LWRP

attribute-cookbook.md, providers/openshift_deploy_router.rb, recipes/master_config_post.rb, resources/openshift_deploy_router.rb
This PR refactors the router-related execute resources in recipe[master_config_post] into a new `openshift_deploy_router` LWRP. Even if the new LWRP does not support any attributes for the moment, I think the pattern is consistent with the other addon LWRPs: `openshift_deploy_registry` and `openshift_deploy_metrics`,
It will also make it easier to configure the router in the future (eg. to specify custom default certificate) and will simplify my wrapper cookbooks.
=> Refactor router-related resources to new openshift_deploy_router LWRP

attribute-cookbook.md, providers/openshift_deploy_registry.rb, recipes/master_config_post.rb, resources/openshift_deploy_registry.rb
Moved the hardcoded registry volume claim name in openshift_deploy_registry LWRP to an explicit attribute. Backward compatibility is preserved.
=> Move registry persistent_volume_claim name to explicit LWRP attribute

.kitchen.yml, providers/openshift_deploy_metrics.rb, providers/openshift_deploy_registry.rb, providers/openshift_deploy_router.rb, recipes/node.rb, templates/default/master.yaml.erb, templates/default/node.yaml.erb
As promised in #51, this PR makes this cookbook compatible with the recently released Openshift Origin 1.4.x. I will be adding changeset (and editing the description of this PR) as I successfully deploy more components of the platform.
Note: I use the experimental openshift v1.4.1 packages from the buildlogs centos paas repository (see openshift/origin#12567).
To test, check the 'origin-1.4.x' branch of my Vagrant VM: https://github.com/PerfectMemory/origin-provision-bug-demo . or use the kitchen integration test of this project.
I have successfully deployed and tested so far:
Not in this PR but manually verified:
It would be nice to find out if the main configuration files (master-config.yml, scheduler.json, node-config.yaml) have changed between OSE v1.3.x and OSE v1.4.x , but for now …
=> Support for Openshift Origin v1.4.x

providers/openshift_deploy_registry.rb, providers/openshift_deploy_router.rb
In multi-node setup, where the value for the `node['cookbook-openshift3']['openshift_common_default_nodeSelector']` is different from `region=infra` (the default value for router/registry node selector), the cookbook will create router and registry dcs, but those won't run any pods. According to `oc describe dc/router -n default` the reason is that "pod node label selector conflicts with its project node label selector".
As explained in https://blog.chmouel.com/2015/09/23/openshift-default-router-on-master-nodes-but-no-others/, the solution is to annotate the `default` namespace to look like this:
```yaml
apiVersion: v1
kind: Namespace
metadata:
annotations:
openshift.io/node-selector: region=infra
```
=> Annotate registry/router namespace to use region=infra node-selector

attribute-cookbook.md, attributes/default.rb
Some attributes from this cookbook appear not to be used anymore:
```
$ for i in $(rgrep ^default attributes* | grep cookbook-openshift3 | cut -d\' -f4); do fgrep -r $i $(ls | egrep -v '(attributes|attribute-cookbook.md|CHANGELOG.md)') -q || echo "Unused attribute: ${i}" ; done
Unused attribute: use_params_roles
Unused attribute: openshift_master_cluster_password
Unused attribute: openshift_common_node_dir
Unused attribute: openshift_common_reverse_svc_ip
Unused attribute: openshift_common_infra_project
Unused attribute: openshift_common_svc_names
Unused attribute: openshift_docker_insecure_registry_arg
Unused attribute: openshift_master_etcd_url
Unused attribute: openshift_master_certs_no_etcd
Unused attribute: openshift_node_label
Unused attribute: erb_etcdClientInfo_urls
Unused …
```
=> Remove a bunch of unused attributes

recipes/node.rb, test/inspec/shared/12_directory_permissions_test.rb
I recently discovered that in certain configurations:
- the `/etc/origin/node` directory has incorrect owner (the vagrant user)
- upgrading the `origin-node` package resets those permissions and breaks access from unprivileged users to the public origin ca certificate (used to `oc login --certificate-authority=/etc/origin/node/ca.crt`).
This PR solves the issue and adds integration test to ensure that permissions of `/etc/origin/node` directory remains correct at all times.
I use the excellent [vagrant-cachier](https://github.com/fgrehm/vagrant-cachier) plugin. This plugin supports chef, and relocates the location of `Chef::Config[:file_cache_path]` to a Virtualbox shared directory on the host; as a consequence every file created under `Chef::Config[:file_cache_path]` ends up with its …
=> Fix permissions within the /etc/origin/node directory

attribute-cookbook.md, attributes/default.rb, templates/default/master.yaml.erb
This PR allows to set:
```yaml
kubernetesMasterConfig:
apiServerArguments:
deserialization-cache-size:
- "1000"
```
In master.yaml, as recommended in https://docs.openshift.com/container-platform/3.3/install_config/install/prerequisites.html#production-level-hardware-requirements openshift/openshift-docs#2542
This parameter is important for us, because we're hit by [this](https://bugzilla.redhat.com/show_bug.cgi?id=1323733) bug, where the openshift master uses huge amount of memory until the oom-killed joins the party.
=> Allow to configure the master api deserialization cache size parameter.

.kitchen.yml, README.md, providers/openshift_deploy_metrics.rb, test/inspec/shared/24_feature_hosted_metrics_test.rb, test/roles/openshift3-base.json
Here are my integration tests for the "hosted metrics" feature. You will notice that I removed the busy wait for the metrics to be deployed in `providers/openshift_deploy_metrics`, this was not consistent with the manner we deployed the other addons and it made my tests very fragile.
=> Add integration test for hosted metrics feature

.kitchen.yml
This PR disables the experimental CentOS PaaS repository that I used while developing the Openshift Origin 1.4.x PR #60.
Please do NOT MERGE until the Origin 1.4.1 packages have made it to the stable CentOS PaaS repository at http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/ , that is when https://github.com/openshift/origin/issues/12567 is closed.
=> Use stable CentOS PaaS repository during tests

attributes/default.rb
This PR makes the cookbook use the stable CentoOS PaaS repository again.
For information, v1.4.1 packages have been pushed to the stable repository last night.
=> Revert e168f9b, use stable repository URLs again

providers/openshift_create_pv.rb, providers/openshift_deploy_metrics.rb, providers/openshift_deploy_registry.rb, providers/openshift_deploy_router.rb, providers/openshift_redeploy_certificate.rb, recipes/master_config_post.rb
This PR directly uses `/etc/origin/master/admin.kubeconfig` to authenticate oc commands in LWRP and in `recipe[cookbook-openshift3::master_config_post]` instead of:
- copying that file into the chef cache directory
- using the copy (using the cwd attribute of execute resource)
- then deleting the copy at the end of `recipe[cookbook-openshift3::master_config_post]`.
I believe there should be no breakage from this change since:
- by definition, the `/etc/origin/master/admin.kubeconfig`  preexisted the copy in `Chef::Config[:file_cache_path`
- chef run as root (so should have no problem to run `oc` commands that need the file unless these commands are run as a non-root user, which is not the case in this cookbook so far)
I tested the changed with both the kitchen tests and my own VMs, they …
=> Directly use /etc/origin/master/admin.kubeconfig instead of coping it.

recipes/default.rb, recipes/etcd_cluster.rb
The `etcd-service` was defined in the default recipe and only used/notified in the etcd_cluster recipe. As a consequence of the double definition of the resource, a CHEF-3694 error was triggered when deploying in Openshift_HA mode.
Log here:
```
==> master: Deprecated features used!
==> master:   Cloning resource attributes for service[etcd-service] from prior resource (CHEF-3694)
==> master: 
==> master: Previous service[etcd-service]: /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/default.rb:27:in `from_file'
==> master: Current  service[etcd-service]: /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/etcd_cluster.rb:187:in `from_file' at 1 location:
```
=> Fix CHEF-3694 with etcd-service service defined in 2 places while used in 1.

.kitchen.yml, CONTRIBUTING, README.md, test/roles/openshift3-base-ose12.json, test/roles/openshift3-base-ose13.json, test/roles/openshift3-base-ose14.json
This PR expands the kitchen tests to test the standalone/cluster-native installation of OSE v1.4.1, v1.3.3 and v1.2.1 . It implements #85.
Note: while running my tests, I confirm that OSE 1.2.x support needs more work (see #76).
Also, I edited the README to recommend locking down the ose_version, ose_major_version and docker_version. I think that in the future we should make the ose_version mandatory (and maybe calculate the ose_major_version from it).
=> Expand .kitchen.yml to test OSE v1.4.1, v1.3.3 and v1.2.1

providers/openshift_redeploy_certificate.rb
Noticed this when testing reprovisioning of certs. Removing .kube/config means it gets re-provisioned in the later include.
=> Remove root kubeconfig when re-provisioning certs

attribute-cookbook.md, attributes/default.rb, templates/default/node.yaml.erb
cAdvisor port and read-only port kubelet arguments allows for some monitoring integrations to be done with OpenShift's underlying Kubernetes metrics.
=> Added cAdvisor port and read-only port for kubelet arguments

attribute-cookbook.md, attributes/default.rb, recipes/master_cluster.rb, recipes/master_standalone.rb
This PR adds ability to securely specify custom master CA certificate which will be used to generate all other certificates (master server, kubelet, router, registry, etc). So all your OpenShift installation will be  automatically trusted by everybody who trusts that custom CA.
Basically this is a port of OpenShift Ansible playbook [openshift_ca](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_ca/tasks/main.yml).
=> Added custom master CA certificate

README.md, attributes/cloud_provider.rb, recipes/master_cluster.rb, recipes/master_standalone.rb
This PR adds support for AWS cloud provider integration using proper IAM policies and eliminates the need to provide raw AWS credentials within Chef encrypted data bags. So now two options for AWS integration are supported: credentials based and IAM based.
=> Add support for AWS IAM based integration

providers/openshift_create_master.rb
I want to expose the openshift console using an official wildcard certificate, by declaring the certificate file and key in `node['cookbook-openshift3']['openshift_master_named_certificates']`.
The certificate I have is special because the common name is also listed in the alternative names:
```sh
$ openssl x509 -in wildcardcert.pem -text | egrep -A1 'Subject:|Alternative Name'
Subject: OU=Domain Control Validated, CN=*.cloud.acme.com
Subject Public Key Info:
--
X509v3 Subject Alternative Name: 
DNS:*.cloud.acme.com, DNS:cloud.acme.com
```
As a result, this cookbook generates the following in /etc/origin/master/master-config.yml:
```yaml
...
servingInfo:
...
namedCertificates:
- certFile: /etc/ssl/acme.pem
keyFile: /etc/ssl/acme.key
names:
- "*.cloud.acme.com"
- "*.cloud.acme.com"
- …
```
=> Fix master named certificates when certificate CN is also listed in alternative names.

recipes/common.rb
By default, the http server used to transfer the generated certificates listens to `0.0.0.0:9999` on the first openshift master and/or etcd master. This is insecure since anyone can get the generated certificates if the xfer servers have a public IP address.
This PR makes the http server only listen to the IP address configured in the attributes which hopefully is not publicly reachable. It should not break usage of the cookbook since every resource which retrieves the generated servers uses `node['cookbook-openshift3']['master_servers'][0]['ipaddress']`, which is the address we listen on.
Before this PR:
```sh
[root@master ~]# netstat -ntlp | grep :9999
tcp6       0      0 :::9999                 :::*                    LISTEN      1156/httpd          
```
After this PR:
```sh …
```
=> Make the xfer http server listen only on specific addresses instead of 0.0.0.0

recipes/etcd_cluster.rb, recipes/master_cluster.rb
This PR should fix #101 .
Note: I used filesystem copy instead of symlink because the copied files will be used in a tarball, so using symlink would not work.
=> Replace most hard link usage with local copy; fixes #101.

recipes/master_cluster.rb
This PR fixes the following CHEF-3694 warning:
```sh
Deprecated features used!
Cloning resource attributes for yum_package[origin] from prior resource
Previous yum_package[origin]: /var/chef/cache/cookbooks/cookbook-openshift3/recipes/master.rb:50:in `from_file'
Current  yum_package[origin]: /var/chef/cache/cookbooks/cookbook-openshift3/recipes/master_cluster.rb:213:in `from_file' at 1 location:
- /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/resource_cloning.rb:58:in `emit_cloned_resource_warning'
See https://docs.chef.io/deprecations_resource_cloning.html for further details.
```
The fix was simple, remove the package resource in `recipe/master_cluster.rb`, because nowadays that recipe is always included from `recipe/master.rb`, after the affected resource has been …
=> Fix CHEF-3694 warning due to redundant package resource

.kitchen.yml, attribute-cookbook.md, attributes/default.rb, providers/openshift_create_master.rb, recipes/master_cluster.rb
Note: this PR builds on top of #107 .
When trying to expose the openshift console under a public URL that uses a real certificate (not one managed by the openshift CA), I found out that `node['cookbook-openshift3']['openshift_master_api_url']` cannot use a certificate that is not managed by the openshift CA.
This is the difference between the `openshift_master_public_api_url` and `openshift_master_api_url` attributes: the former is public (and can use a public certificate) while the latter is internal to openshift (and must use a certificated signed by the openshift CA). A consequence is that the hostname used in `node['cookbook-openshift3']['openshift_master_api_url']` cannot be included in the list of master named certificates, even if the certificate lists that value by accident. For …
=> Distinct hostnames for internal and public api access

attribute-cookbook.md, attributes/default.rb, providers/openshift_deploy_router.rb
This PR implements #103.
Its scope is much more reduced than I thought, because the cookbook already pre-creates the router-certs secrets with the generated certificates. I only had to move the hardcoded certificate names into an attribute, that I can override in my roles and voila!
Simple usage:
1. pre-create the certificate and key files on disk before `recipe['cookbook-openshift3::default']` runs
2. have the following attributes configured in a role or environment:
```sh
node['cookbook-openshift3']['openshift_hosted_router_certfile'] = '/path/to/custom/openshift-router.crt"
node['cookbook-openshift3']['openshift_hosted_router_keyfile'] = '/path/to/custom/openshift-router.key"
```
If the router has already been provisioned with the defaults openshift-signed certificates, run:
```
oc …
```
=> Allow to specify custom certificate for hosted router

providers/openshift_create_master.rb
If `openshift_common_public_hostname` resolves to multiple IPs there was continues changes to `corsAllowedOrigins` section at `master-config.yaml` with every Chef client run. 
Fixes #111.
=> Allow public hostname resolve to multiple IPs

.kitchen.yml, recipes/master_cluster.rb, test/inspec/shared/11_functioning_openshift_test.rb
Each openshift master API peer should list their endpoint ip-address in their certificate SANs.
We did not catch this error in the kitchen spec before because we used `node['cookbook-openshift3']['openshift_common_api_hostname'] = <ipaddress>`, resulting in the ipaddress being included in the certificate SANs automatically.
Using an HA deployment of openshift, where `node['cookbook-openshift3']['openshift_common_api_hostname'] = <some resolvable dns name pointing to at least one master api instance>`.
I want to make the prometheus monitoring system scrape the `kubernetes-apiserver` target defined in the sample configuration file here: https://github.com/prometheus/prometheus/blob/14d0604aba95c7bb434f3a7687f7903bbe4fd81f/documentation/examples/prometheus-kubernetes.yml#L15-L48 . The …
=> Make master api peers list their endpoint ipaddress in their certificate SANs

recipes/master_standalone.rb
This PR is the equivalent of #119 but for standalone master deployments.
Without this PR:
```
[root@standalone-master master]#  curl --cacert /etc/origin/node/ca.crt https://192.168.122.12:8443
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```
With this PR:
```sh
[root@standalone-master master]#  curl --cacert /etc/origin/node/ca.crt https://192.168.122.12:8443
{
"paths": [
"/api",
"/api/v1",
"/apis",
"/controllers",
"/healthz",
"/healthz/ping",
"/healthz/ready",
"/metrics",
"/oapi",
"/oapi/v1",
"/swaggerapi/"
]
}
```
=> Include the openshift standalone masterIP in the SANs of master.server.crt

recipes/master_cluster.rb
This PR should fix for #122 , where the copy of some master certificates would fail on openshift v1.5.0 because some certificate files which existed in v1.4.1 , are gone in v1.5.0. The PR should be backward-compatible with all openshift versions earlier than v1.5.0.
Here is the differences in the files present in `/etc/origin/master` between openshift v1.4.1 and v1.50, on a fresh installation using this cookbook:
```diff
--- v1.4.1.txt	2017-05-19 13:43:21.977050811 +0200
+++ v1.5.0.txt	2017-05-19 13:43:06.240996513 +0200
@@ -22,12 +22,6 @@
openshift-master.crt
openshift-master.key
openshift-master.kubeconfig
-openshift-registry.crt
-openshift-registry.key
-openshift-registry.kubeconfig
-openshift-router.crt
-openshift-router.key
-openshift-router.kubeconfig
policy.json
scheduler.json …
```
=> Only copy master certificates which exist in /etc/origin/master

recipes/etcd_cluster.rb, recipes/master_cluster.rb
This PR removed duplicated code in `recipe[master_cluster]` which is supposed to initialize the etcd ca directory, work which has already been done by `recipe[etcd_cluster]` which is included earlier in the run list.
This fixes the CHEF-3694 spam reported in #121 , which I report again below:
```sh
Deprecated features used!
Cloning resource attributes for template[/etc/etcd/ca/openssl.cnf] from prior resource
Previous template[/etc/etcd/ca/openssl.cnf]: /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/etcd_cluster.rb:26:in `from_file'
Current  template[/etc/etcd/ca/openssl.cnf]: /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/master_cluster.rb:27:in `from_file' at 1 location:
- /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/master_cluster.rb:27:in …
```
=> Remove duplicated code between etcd_cluster and master_cluster recipes.

recipes/master_cluster.rb
A tiny PR to fix a recently introduced CHEF-3694 error due to some certificate file names being iterated twice (because the name is both listed in `node['cookbook-openshift3']['openshift_master_certs']` and added in openshift version-specific case).
Typical symptoms seen in chef-client output:
```sh
Cloning resource attributes for remote_file[/var/www/html/master/generated_certs/openshift-rtlbrumamdvrs02/service-signer.crt] from prior resource
Previous remote_file[/var/www/html/master/generated_certs/openshift-rtlbrumamdvrs02/service-signer.crt]: /var/chef/cache/cookbooks/cookbook-openshift3/recipes/master_cluster.rb:191:in `block (2 levels) in from_file'
Current  remote_file[/var/www/html/master/generated_certs/openshift-rtlbrumamdvrs02/service-signer.crt]: …
```
=> Fix CHEF-3694 warning with master certificates

recipes/master_config_post.rb
This PR fixes the following CHEF-3694 error:
```sh
==> master:   Cloning resource attributes for execute[Wait up to 30s for nodes registration [Size : 3]] from prior resource
==> master: Previous execute[Wait up to 30s for nodes registration [Size : 3]]: /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/master_config_post.rb:77:in `block in from_file'
==> master: Current  execute[Wait up to 30s for nodes registration [Size : 3]]: /tmp/vagrant-cache/chef/cookbooks/cookbook-openshift3/recipes/master_config_post.rb:77:in `block in from_file' at 1 location:
==> master:     - /tmp/vagrant-cache/chef/cookbooks/poise/files/halite_gem/poise/helpers/resource_cloning.rb:58:in `emit_cloned_resource_warning'
==> master:    See https://docs.chef.io/deprecations_resource_cloning.html for …
```
=> Fix CHEF-3694 warning that triggered while waiting for node registration

providers/openshift_deploy_registry.rb
I suspect environment is run before the LWRP starts, resulting in a failure going to stderr, and the registry ip being blank.
Simply placing it inline works.
=> issue #138 backticks in environment doesn't work

recipes/node.rb
=> enable and start dnsmasq, ignoring failures

Jenkinsfile, attributes/default.rb, recipes/certificate_server.rb, recipes/common.rb, recipes/etcd_cluster.rb, recipes/master.rb, recipes/master_cluster.rb, recipes/node.rb, recipes/validate.rb
This is an attempt to allow the admin to have a separate server where certificates are created.
It is designed to be back-compatible, where the default is to go back to the first-master method.
If a separate certificate_server is specified, then the chef recipes can run on there to create the certs and serve them from the same endpoint. Or the certs can be created by some other method and left placed there for download.
The motivation behind this was to twofold:
- Remove the requirement for a 'static' first master that also held the certificates - we had a first master that needed to be moved and this complicated things.
- Give the opportunity in future to allow a third party application to generate and serve the certificates from an arbitrary location
I have added a test case for a …
=> certificate_server separation

recipes/validate.rb
This PR fixes the following cookstyle offense:
```sh
$ cookstyle 
Inspecting 64 files
.........................C......................................
Offenses:
recipes/validate.rb:25:94: C: Use t.casecmp(node['cookbook-openshift3']['openshift_metrics_cassandra_storage_type']).zero? instead of t.casecmp(node['cookbook-openshift3']['openshift_metrics_cassandra_storage_type']) == 0.
unless node['cookbook-openshift3']['openshift_metrics_cassandra_storage_types'].any? { |t| t.casecmp(node['cookbook-openshift3']['openshift_metrics_cassandra_storage_type']) == 0 }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
64 files inspected, 1 offense detected
```
=> Cookstyle fix

.kitchen.yml, attribute-cookbook.md, attributes/default.rb, providers/openshift_deploy_router.rb, recipes/master_config_post.rb, resources/openshift_deploy_router.rb, test/inspec/shared/22_feature_hosted_router_test.rb
This PR allows to pass custom arguments when deploying the hosted router with `oc adm router`.
My objective is to deploy the openshift hosted router with the prometheus metrics exposed, as documented in https://docs.openshift.com/container-platform/3.5/install_config/router/default_haproxy_router.html#exposing-the-router-metrics . For this, I need to inject the `--expose-metrics` (and eventually `--metrics-image`) options in the `oc adm router` command line arguments.
My proposal is to add a new attribute `node['cookbook-openshift3']['openshift_hosted_router_options']`, which defaults to empty and allows to define command line fragment that will be passed to `oc adm router` when this cookbook deploys the router.
=> Allow passing custom arguments to `oc adm router` when deploying the hosted router

.kitchen.yml, README.md
This PR updates the CentOS version used in kitchen tests from 7.2 to 7.4 (current stable).
=> Update CentOS version in .kitchen.yml to v7.4 (from v7.2)

attributes/default.rb, templates/default/master.yaml.erb
Add possibilty to give event-ttl argument for api server.
Our ops team want the possibility to increase the retention period for events, e.g. 
event-ttl:
- "24h"
(default 1h0m0s)
=> Event retention

templates/default/master.yaml.erb
This PR fixes a regression that I introduced 2 weeks ago (see https://github.com/IshentRas/cookbook-openshift3/blame/master/templates/default/master.yaml.erb#L71-L76 ).
The problem happens when origin-master is deployed in standalone mode, using the embedded etcd instance:
- the etcdConfig is configured in /etc/origin/master/master-config.yml to point etcd client at `node['cookbook-openshift3']['openshift_common_api_hostname']` port 4001.
- that openshift_common_api_hostname may not always resolve to the local machine; in the case of a legacy server, it resolved to an external ipaddress, on which is listening a proxy which handles traffic for ports 80 and 443 but NOT for the etcd ports 4001 and 7001
- in that case, the origin-master service will refuse to boot because it cannot join the …
=> Fix regression with etcd host~ in standalone master-config

.kitchen.yml, recipes/master_cluster.rb, test/inspec/shared/11_functioning_openshift_test.rb
This PR fixes provisioning the cluster in HA mode (cluster-native) when both `node['cookbook-openshift3']['openshift_common_api_hostname']` and `node['cookbook-openshift3']['openshift_common_public_hostname']` are provided and they have a different value.
Why have a different value for api and public hostname?
- the public hostname is associated with a public SSL certificate (signed by a public CA), so that clients can use the openshift console without having to accept a self-signed certificate in their browser
- the api hostname is for internal use and uses certificates signed by the openshift CA
In the real world, I configure my attributes like this:
```json
"cookbook-openshift3": {
"openshift_HA": true,
"openshift_cluster_name": "mycluster.example.com",
"master_servers": [ ... ], …
```
=> Fix cluster-native provisioning when common_api_hostname != common_public_hostname

attribute-cookbook.md
This PR follows up to #176 and documents the new attribute.
=> Add the new openshift_master_retain_events attribute in attribute-cookbook.md

test/inspec/shared/11_functioning_openshift_test.rb
The inspec tests are checking for kube-dns reverse working, however this feature only applies to OSE >= v3.6. This PR makes the integration test for that feature conditional.
=> Only test kube-dns reverse DNS feature when OSE major version >= 3.6

attributes/default.rb, attributes/metrics.rb, test/roles/openshift3-base-ose36.json
Some more gardening for this cookbook: update default OSE v3.6 version to v3.6.1 (current stable). I'm already deploying this version successfully, so may as well update the cookbook defaults.
=> Update default OSE v3.6 version to v3.6.1 (from v3.6.0)

recipes/master_cluster.rb
This is a fix to the certserver code.
Previously there was a bug, as the first master would not get all the required certs downloaded.
In the case of a separate certserver, this causes issues where the first master doesn't have the required certs. This change always downloads the certs on the first master come what may (even from itself!).
This has been tested with a certserver configuration and the traditional 'first master' configuration (which will now be the default 'quick' test).
=> Certserver fix 2

.kitchen.yml, README.md, attribute-cookbook.md, test/roles/openshift3-base-ose37.json
This PR enables kitchen tests for OSE v3.7.x.
It also updates README.md and attribute-cookbook.md with OSE v3.7 as default version deployed by the cookbook.
=> Add kitchen test for Openshift Origin v3.7.x

templates/default/service_node-containerized.service.erb, templates/default/service_node.service.erb
This PR is straight port of https://github.com/openshift/openshift-ansible/pull/6843 which fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532960
In short: if the dnsmasq service is restarted on the host, then origin-node service is also restarted (there should be no need IMO). I had noticed the problem a few weeks back but someone already wrote a patch and got it merged in the openshift-ansible playbook, so I do the same on this cookbook.
=> Change dnsmasq Requires to Wants

attribute-cookbook.md, attributes/default.rb, templates/default/service_docker.sysconfig.erb, templates/default/service_master-api.sysconfig.erb, templates/default/service_master-controllers.sysconfig.erb, templates/default/service_master.sysconfig.erb, templates/default/service_node.sysconfig.erb
This PR adds support for deploying openshift on environment where outgoing http/https traffic must go through a proxy. Without it, even if we managed to install openshift, we still would not be able to pull docker images from external registries for example.
Official documentation is here: https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-configuring-global-proxy  . The documented attributes are used by the openshift-ansible playbook to do the dirty work.
The new attributes are:
-  `node['cookbook-openshift3']['openshift_http_proxy']`
- `node['cookbook-openshift3']['openshift_https_proxy']`
- `node['cookbook-openshift3']['openshift_no_proxy']`
All three default to empty string.
When the attributes are non empty, the `HTTP_PROXY`, `HTTPS_PROXY` …
=> Support for http_proxy, https_proxy and no_proxy

recipes/master_cluster.rb, recipes/master_config_post.rb
This fixes the issues seen in test.
The curl to test that the Master API is up now does not need to see an OK, but checks for a zero exit code.
=> API bugfix

.kitchen.yml, test/inspec/shared/22_feature_hosted_router_test.rb
This PR changes the way we test that `node['cookbook-openshift3']['openshift_hosted_router_options']` attribute was properly passed to `oc adm router`.
We used to pass `--expose-metrics` but custom metrics options were removed in OSE v3.10.
Instead, we now use the `--stats-password` option which is supported by every OSE version.
=> Test openshift_hosted_router_options with --stats-password (compatible with all OSE versions)

attributes/default.rb, recipes/node.rb
This PR makes disabling the SWAP on nodes optional (but enabled by default).
Why leave swap enabled even if it makes origin node less reliable? On my workstation, I have limited memory availability yet I want to test multi VM clusters without having random pods inside get OOMKilled. With this PR I can set `node['cookbook-openshift3']['openshift_node_disable_swap_on_host'] = false` in my role attributes and be happy.
=> Make SWAP disabling on nodes optional (but enabled by default).

recipes/master_cluster.rb, recipes/master_config_post.rb, recipes/ng_nodes_certificates.rb, recipes/node.rb, recipes/upgrade_control_plane38_part1.rb, recipes/upgrade_control_plane39_part1.rb, resources/openshift_upgrade.rb
When upgrading a production cluster which uses a `node['cookbook-openshift3']['openshift_master_named_certificates']`, I noticed the code which poll (in different place) for master API being ready fail. This code was not present in version 1.0.6x of this cookbook so I only report it now.
The reason is that the polling code curls the public master API URL endpoint (which uses the named certificate) while specifying the internal kubernetes certificate as `--cacert`. When the public master API URL endpoint uses a certificate signed by a public CA (which is not the internal kubernetes certificate) then the readiness test fails and the chef run too.
Example broken code here: https://github.com/IshentRas/cookbook-openshift3/blob/master/recipes/master_cluster.rb#L222-L226
Proposed fix: always …
=> Poll /healthz/ready using openshift_master_loopback_api_url only

attributes/identity_provider.rb
This PR fixes a recent regression where the `openshift-passwd` file moved to an incorrect directory, thus breaking pre-provisioned htpasswd users.
https://github.com/IshentRas/cookbook-openshift3/blame/master/attributes/identity_provider.rb#L13
=> Fix regression with path of /etc/origin/openshift-passwd

providers/openshift_create_master.rb
This PR fixes #283.
@IshentRas please confirm that presence of PodPreset in the master-config.yml admission plugin config is a actually a bug before merging this.
=> Remove PodPreset injection into openshift master admission plugin config

templates/default/docker-storage.erb
This PR allows to declare arbitrary environment variables inside the `node['cookbook-openshift3']['openshift_node_docker-storage']`, which will be rendered in `/etc/sysconfig/docker-storage-setup`.
Objective : to configure any options listed in https://github.com/projectatomic/container-storage-setup/blob/master/container-storage-setup.conf ; for example, automatic extension of the docker LVM thin pool could b e be done by setting:
```
default['cookbook-openshift3']['openshift_node_docker-storage'] = {
"VG": "vg",
"DATA_SIZE": "50G",
"AUTO_EXTEND_POOL": false
}
```
=> Allow configuring any option supported by docker-storage-setup

resources/openshift_master_pkg.rb
When installing OSE v3.9.0 using the latest released version of this cookbook (v2.1.2), the converge fails because the cookbook tries to install v3.9.0 of package `tuned-profiles-origin-node` which does not exist on https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin39/
Note: for earlier OSE versions (from 3.6 to 3.8) the package exists on the repositories.
This PR filters out the `tuned-profiles-origin-node` from the list of packages to install on the server when the current ose_major_version is 3.9.
Full chef stack trace before the PR:
```
* iptables_rule[firewall_certificate] action enable
* template[/etc/iptables.d/firewall_certificate] action create
- create new file /etc/iptables.d/firewall_certificate
- update content in file /etc/iptables.d/firewall_certificate from …
```
=> Filter out tuned-profiles-origin-node for OSE v3.9 -- it does not exist on repository

recipes/node.rb
This PR fixes the node counterpart of what we fixed in #288 for master, that is that the tuned-profile-origin-node package should not be installed on nodes running OSE >= 3.9, in control_upgrade or in normal mode.
There was existing code but it was broken (it would work when control_upgrade_version is >= 39 but would break when using the ose_major_version which looks like 3.9 and not 39).
=> Filter out tuned-profiles-origin-node for OSE v3.9 (node)

recipes/master_cluster.rb, recipes/master_config_post.rb, recipes/ng_nodes_certificates.rb, recipes/upgrade_control_plane38_part1.rb, recipes/upgrade_control_plane39_part1.rb
This PR forces `environment 'no_proxy' => 'localhost'` for every curl command which polls the openshift master on the loopback url (localhost).
I have a server which has the following environment:
```sh
[root@staging ~]# env | grep proxy
http_proxy=http://192.168.122.1:3128
ftp_proxy=
https_proxy=http://192.168.122.1:3128
no_proxy=192.168.122.1,.staging.example.com
```
Running `chef-client` on this server fails to converge because the `execute[Wait for API to become available]` resources which poll the openshift API server at localhost try to pass through the system http proxy (which has a different localhost than the host running the origin master service).
```sh
Recipe: cookbook-openshift3::master_cluster
* execute[Wait for master api service to start on first master] action run …
```
=> Pool openshift_master_loopback_api_url (localhost) without http proxy

recipes/certificate_server.rb, recipes/common.rb, recipes/etcd_cluster.rb, recipes/master.rb, recipes/master_cluster.rb, recipes/ng_certificate_server.rb, recipes/ng_etcd_cluster.rb, recipes/ng_master.rb, recipes/ng_node.rb, recipes/node.rb
It seems that a restart to iptables is now required to get the iptables rules adopted. If it is restarted later in the script, a race condition emerges where etcd can't start because the other nodes depended on can't download the certificates from the cert server.
This change restarts iptables in all the places where iptables rules are set.
Just testing by hand now.
=> #136 - restart iptables

providers/openshift_deploy_logging.rb
This PR implements support for specifying a whitelist of hosts where the fluentd damonset should run.
Possible values for ` node['cookbook-openshift3']['openshift_logging_fluentd_hosts']`:
- `['--all']` (default, compatible with current behavior): run fluentd on every node
- `{}`, `[]` or `nil`: run fluentd on no node
- `['host1', 'host2']`: run fluentd only on nodes named `host1` or `host2`
I took inspiration from:
- [OSE v3.9 aggregate logging](https://docs.openshift.com/container-platform/3.9/install_config/aggregate_logging.html) for documentation
- [openshift-ansible](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_logging_fluentd/tasks/main.yaml#L204-L227) for implementation
=> Allow to specify fqdn whitelist in `node['cookbook-openshift3']['openshift_logging_fluentd_hosts']`.

templates/default/scheduler.json.erb
I noticed that Local Persistent Volumes are broken when using OSE v3.9 and the current version of this cookbook.
In the origin-node log for one of the nodes which should receive a pod that uses a local persistent volume, the following messages can be seen :
```
Apr 01 16:08:52 backends-3 origin-node[24918]: E0401 16:08:52.113264   24918 reconciler.go:258] operationExecutor.MountVolume failed (controllerAttachDetachEnabled true) for volume "volume-mongodb-backends" (UniqueName: "kubernetes.io/local-volume/dfe58996-5492-11e9-b92c-0800278bc93f-volume-mongodb-backends") pod "mongodb-0" (UID: "dfe58996-5492-11e9-b92c-0800278bc93f") : MountVolume.NodeAffinity check failed for volume "volume-mongodb-backends" (UniqueName: "kubernetes.io/local-volume/dfe58996-5492-11e9-b92c-0800278bc93f-volume-mon …
```
=> Add missing CheckVolumeBinding predicate (fix Local Persistent Volumes for OSE 3.9)
