IshentRas/cookbook-openshift3

- recipes/default.rb
Fixed issue reported here : https://github.com/IshentRas/cookbook-openshift3/issues/5
> Enable HTTPD at startup

- attributes/default.rb
- recipes/common.rb
- recipes/master_cluster.rb
- Add possibilty to disable yum repositories
- Fix permissions for directory (Set to Apache in case of a dodgy umask number)
- Fix etcd certificate (Simplify the call for peers members)
- Add possibilty to specify a version to be installed for docker
> Fix several issues

- attributes/default.rb
- templates/default/node.yaml.erb
Based on 3.1 docs in prep for future work. Untested.
> node garbage collection

- README.md
- scripts/origin_deploy.sh
- bomb out on error
- script correction in README
> minor corrections

- recipes/master_config_post.rb
> Removed redundant guard clause

- .kitchen.yml
- test/inspec/shared/21_feature_persistent_storage_test.rb
- test/inspec/shared/22_feature_hosted_router_test.rb
- test/inspec/shared/23_feature_hosted_registry_test.rb
- test/roles/openshift3-base.json
This PR adds integration test for a the following features of this cookbook:
- persistent_storage
- hosted router
- hosted registry
> Persistent storage registry router tests

- CHANGELOG.md
- attributes/default.rb
- providers/openshift_deploy_router.rb
- templates/default/service_docker.sysconfig.erb
> Support multiple dns search option entries

- recipes/etcd_cluster.rb
- recipes/master.rb
A trivial PR to make the `cookstyle` tool happy.
> More cookstyle fixes

- templates/default/service_docker.sysconfig.erb
Space missing from dns search items.
> bugfix: add a space to the dns_search for loop

- recipes/node.rb
Empty data bag params for AWS deployment caused an error while provisioning nodes. Fixed
> Fix AWS issue with empty data bag

- README.md
- providers/openshift_redeploy_certificate.rb
- recipes/upgrade_x2_x3.rb
This PR contains multiple fixes and documentation related to the  adhoc redeploy certificates recipe
> Document adhoc redeploy certificates recipe

- recipes/master_cluster.rb
This PR should fix #131 , please confirm @ianmiell .
> Enable *-master-controllers and *-master-api services on master nodes.

- README.md
- attribute-cookbook.md
- attributes/default.rb
- attributes/metrics.rb
- files/default/import_jks_certs.sh
- providers/openshift_deploy_metrics.rb
- providers/openshift_deploy_registry.rb
- recipes/default.rb
- recipes/master_config_post.rb
- recipes/validate.rb
- resources/openshift_deploy_metrics.rb
- templates/default/hawkular_cassandra_rc.yaml.erb
- templates/default/hawkular_metrics_rc.yaml.erb
- templates/default/heapster.yaml.erb
- templates/default/master.yaml.erb
- templates/default/pvc.yaml.erb
- templates/default/rolebinding.yaml.erb
- templates/default/route.yaml.erb
- templates/default/secret.yaml.erb
- templates/default/service.yaml.erb
- templates/default/serviceaccount.yaml.erb
- Support for OCP Metrics
- Restrict to 1 Cassandra PODS
> Openshift hosted metrics

- providers/openshift_create_master.rb
- recipes/common.rb
- recipes/default.rb
- recipes/master_cluster.rb
- recipes/master_standalone.rb
- recipes/node.rb
This PR contains suggestions for code changes following an internal review here.
Two items of work:
- replace ruby blocks with service resources
- add a timeout of du command, as that can hang
> Suggestions

- providers/openshift_create_pv.rb
- providers/openshift_deploy_registry.rb
- providers/openshift_deploy_router.rb
- recipes/master_config_post.rb
This corrects a lot of errors seen in the chef output in my tests.
I have desk-tested and this all appears to work. Doing fuller tests now.
> admin.kubeconfig made unambiguous

- providers/openshift_delete_host.rb
- recipes/master_cluster.rb
> Fix issue for starting master

- upgrade-process.md
> Minor changes to upgrade docs

- README.md
- attribute-cookbook.md
- metadata.rb
> Typo fixes

- templates/default/firewall_etcd.erb
- templates/default/firewall_lb.erb
- templates/default/firewall_master.erb
- templates/default/firewall_master_cluster.erb
- templates/default/firewall_node.erb
- Modify the firewall state (NEW -> NEW,ESTABLISHED)
- Fix issue reported in : https://github.com/IshentRas/cookbook-openshift3/issues/178
> Change FW state

- recipes/validate.rb
Check there's a first_etcd set
> first_etcd check

- recipes/validate.rb
Signed-off-by: Christopher P. Maher <chris@mahercode.io>
Hello! This is a PR that fixes #229 . It's a pretty simple logic fix. 
Tested locally, runs great. Please let me know if more is needed or if there are any questions. Thanks for the kickass cookbook BTW! This is making my deployments a dream @IshentRas !
> etcd validation detection fix (Fixes #229)

- attributes/default.rb
- providers/openshift_deploy_registry.rb
- recipes/docker.rb
- templates/default/service_docker.sysconfig.erb
> Fix issue reported by 244

- attributes/update.rb
- recipes/upgrade_control_plane37.rb
- recipes/upgrade_control_plane37_part2.rb
> Fix issue reporting by 241

- .rubocop.yml
- attributes/default.rb
- libraries/openshift_helper.rb
- recipes/validate.rb
Some trivial fixes to make `cookstyle` pass (at least with the rubocop/cookstyle bundled with chef-dk v3.10).
> Cookstyle fixes

- providers/openshift_deploy_logging.rb
This PR fixes #258.
As a reminder, the issue was that the nodes were labeled logging-infra-fluentd=true only the first time (when the logging component is provisioned on the first master) and not everytime a new node is added.
**Please do NOT merge before #260, so that I get a chance to rebase this**
> Label logging-infra-fluentd nodes everytime a node is added, not only the first time

- recipes/ng_node.rb
- resources/openshift_create_node_config.rb
This PR fixes a couple trivial bugs I encountered while trying to provision OSE v3.10 using the "ng" recipes of this cookbook.
> Misc fixes to ng v310 recipes
